version: "3.7"
services:
  grafana:
    image: grafana/grafana:6.4.2
    ports:
      - 3000:3000/tcp
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards/:/var/lib/grafana/dashboards/
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.13.0
    ports:
      - 9090:9090/tcp
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    ports:
      - 8000:80/tcp
    restart: unless-stopped

  postgres:
    image: postgres:12.0-alpine
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432/tcp
    restart: unless-stopped

  bot:
    build: ./bot
    environment:
      BACKEND: http://host.docker.internal:5000
    restart: unless-stopped
